import { Component, OnInit } from '@angular/core';
import { Cast } from 'src/app/models/cast';

@Component({
  selector: 'app-list',
  templateUrl: './list.component.html',
  styleUrls: ['./list.component.scss']
})
export class ListComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  casts: Cast[] = [
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
    {
      cast_id: 1111,
      shop_id: 1,
      entry_date: new Date('2016-6-2'),
      source_name: 'XXXXXX',
      introducer_id: 1,
      agreement_id: 1,
      hourly_salary: 3000,
      point: 20,
      likely_winner: 0.9,
      inside_the_hall: 0.8,
      attendant: 1.1,
      manager: 1,
      dispatch_id: null,
      cast_name: 'NNNN',
      tel_no: '',
      zip_code: '',
      address: '',
      tatemono: '',
      del_flg: false
    },
  ]
}
